---
apiVersion: v1
kind: ConfigMap
metadata:
  name: backend
  namespace: linkto
data:
  PORT: "8080"
  SPRING_REDIS_HOST: redis
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend
  namespace: linkto
data:
  BACKEND_HOST: backend
  BACKEND_PORT: "8080"
